services:
  mongodb:
    image: mongo:6
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: app_container
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:

